plugins:
  - skipBotEvents: true
    uses:
    - plugin: http://127.0.0.1:4000
      with:
        autoTransferMode: false
        evmNetworkId: 11155111
        evmPrivateEncrypted: "yjqiEBcnZOmHcLteVxNapEzWJtXpSzx4lYrGgh5HHgbCXZcq-MZ26tm6LuTGScq76L9LXlHf650Z9upWipMhTYBaUFAOqVYsDT3TzAjf4KUmKiMSC4Q_YUTk04q5uP84hZndIYOvdF0uz1Z2Vvv2zHb8cJybL-J23eg"
        erc20RewardToken: "0x2C78Dd981bFe7EaDd758A878d9655B806394185c"
        dataCollection:
          maxAttempts: 10
          delayMs: 10000
        incentives:
          requirePriceLabel: true
          limitRewards: true
          collaboratorOnlyPaymentInvocation: true
          contentEvaluator:
            llm:
              model: "gpt-4" # Model identifier
              endpoint: "https://openrouter.ai/api/v1" # Configurable LLM endpoint
              tokenCountLimit: 124000 # Adjustable token limit
              maxRetries: 3 # Number of retries for rate limits/errors
            multipliers:
              - role: [ISSUE_SPECIFICATION]
                relevance: 1
              - role: [PULL_AUTHOR]
                relevance: 1
              - role: [PULL_ASSIGNEE]
                relevance: 1
              - role: [PULL_COLLABORATOR]
                relevance: 1
              - role: [PULL_CONTRIBUTOR]
                relevance: 1
          userExtractor:
            redeemTask: true
          permitGeneration: {}
          githubComment:
              post: true
              debug: false
          dataPurge:
            skipCommentsWhileAssigned: all
          reviewIncentivizer:
            baseRate: 100
            conclusiveReviewCredit: 25
          formattingEvaluator:
            wordCountExponent: 0.85
            multipliers:
              - role: ["ISSUE_SPECIFICATION"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["ISSUE_AUTHOR"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.2
              - role: ["ISSUE_ASSIGNEE"]
                multiplier: 0
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0
              - role: ["ISSUE_COLLABORATOR"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["ISSUE_CONTRIBUTOR"]
                multiplier: 0.25
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["PULL_SPECIFICATION"]
                multiplier: 0
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0
              - role: ["PULL_AUTHOR"]
                multiplier: 2
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.2
              - role: ["PULL_ASSIGNEE"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["PULL_COLLABORATOR"]
                multiplier: 1
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
              - role: ["PULL_CONTRIBUTOR"]
                multiplier: 0.25
                rewards:
                  html:
                    br: { score: 0, countWords: true }
                    code: { score: 5, countWords: false }
                    p: { score: 0, countWords: true }
                    em: { score: 0, countWords: true }
                    img: { score: 5, countWords: true }
                    strong: { score: 0, countWords: false }
                    blockquote: { score: 0, countWords: false }
                    h1: { score: 1, countWords: true }
                    h2: { score: 1, countWords: true }
                    h3: { score: 1, countWords: true }
                    h4: { score: 1, countWords: true }
                    h5: { score: 1, countWords: true }
                    h6: { score: 1, countWords: true }
                    a: { score: 5, countWords: true }
                    li: { score: 0.5, countWords: true }
                    ul: { score: 1, countWords: true }
                    td: { score: 0, countWords: true }
                    hr: { score: 0, countWords: true }
                    pre: { score: 0, countWords: false }
                    ol: { score: 1, countWords: true }
                  wordValue: 0.1
